feat: add 3 template
vitejs/awesome-vite pull request #266
Opened 2021-09-11 01:36 UTC by Innei

> Please make sure all the requirements are satisfied, otherwise the PR could be closed without further notice.

## Checklist

- [x] Title as described.
- [x] Make sure you put things in the right category.
- [x] The description of your item should be a sentence with less than 24 words.
- [x] Omit unnecessary words already provided in the context (e.g. `for Vite`, `a Vite plugin`).
- [x] Always add your items to the end of a list.

### Plugins/Tools

- [ ] The plugin/tool is working with **Vite 2.x and onward**.
- [ ] The project is Open Source.
- [ ] The project follows the [Vite Plugins Conventions](https://vitejs.dev/guide/api-plugin.html#conventions).
- [ ] The plugin uses Vite specific hooks and can't be implemented as a [Compatible Rollup Plugin](https://vitejs.dev/guide/api-plugin.html#rollup-plugin-compatibility).
- [ ] The repo should be at least 30 days old.
- [ ] The documentation is in English.
- [ ] The project is active and maintained (projects that inactive for longer that 6 months will be removed without further notice).
- [ ] The project accepts contributions.
- [ ] Not a commercial product.

### Starter Templates

- [x] The starter template is working with **Vite 2.x and onward**.
- [x] The documentation is in English.
- [x] The starter template most provide enough instructions / documentation about how to start up and what's is included.
- [x] A screenshot or a live demo should be included.
- [x] The repo should be at least 30 days old.
- [x] Should be differentiable from the existing starter templates. 

### Apps/Websites

- [ ] The website is available without errors and load in a reasonable amount of time.
- [ ] The website must be Open Source and showing it's using Vite intensively.
- [ ] The website is original and not too simple. For that reason, blogs and simple landing pages are rejected.

2021-09-13 05:54 UTC, Scrum requested changes

2021-09-13 05:54 UTC, Scrum commented on README.md
> +- [naive-ui-dashboard-template](https://github.com/Innei/naive-ui-dashboard-template) - UI friendly, Vue 3 + TSX + TailwindCSS 2 JIT + PostCSS + Naive UI, Cool!
Make two documentation, one of which should be in English and be the main one

2021-09-23 10:17 UTC, Scrum approved these changes

2021-09-23 10:18 UTC, merged

2021-09-23 18:01 UTC, web2033 commented
This brings back those emoji / https://github.com/vitejs/awesome-vite/pull/268
I think they are redundant. As well as words like `so fast!`, `crazy fast! `, `Cool!`