Add vite-wind starter template
vitejs/awesome-vite pull request #62
Opened 2021-01-14 09:25 UTC by boussadjra

### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [ x] Pull request template structure not broken

### `Type`

> ℹ️  What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Fix
- [ x] Feature 

### `Checklist`

> ℹ️  Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](https://github.com/vuejs/awesome-vue/blob/master/.github/contributing.md).

> 👉  _Put an `x` in the boxes that apply._

- [x ] Title as described.
- [x ] Make sure you put things in the right category!
- [ x] Always add your items to the end of a list.
- [x ] Your plugin/tool is working with Vite 2.0 and onward.

#### `Open Source`

- [x ] Link description does not contain a link to an author / third-party resource
- [ x] The documentation (README) contains a description of the project, illustration of the project with a demo or screenshots and a CONTRIBUTING section
- [x ] The documentation is in English.
- [x ] The project is active and maintained.
- [x ] The project accepts contributions.
- [ x] Not a commercial product

#### `Apps/Websites`

- [x ] The website is available without errors or ssl certificate problems, and load in a reasonable amount of time.
- [x ] The website is using Vite intensively.
- [x ] The website is original and not too simple. For that reason, blogs and simple landing pages are rejected.
- [ ] A commercial product using Vite, provided that guests could reasonably check out how Vite was used A commercial product using Vite, provided that guests could reasonably check out how Vite was used (i.e. A headless CMS which uses Vite for the Admin/editor Area and offers a free tier).

2021-01-14 11:36 UTC, innocenzi requested changes

2021-01-14 11:36 UTC, innocenzi commented on README.md
> +- [vite-wind](https://github.com/boussadjra/vite-wind) - It's a Vue 3 boilerplate based on Tailwindcss + Typescript + Vite + css-pro-layout, it includes +9 components and it supports also the dark mo
```suggestion
- [vite-wind](https://github.com/boussadjra/vite-wind) - Boilerplate with Tailwind CSS, TypeScript, css-pro-layout, 9+ components and dark mode support.
```

2021-01-27 05:04 UTC, antfu requested changes

2021-01-27 05:04 UTC, antfu commented on README.md
> +
Please omit this line.

2021-01-27 05:04 UTC, antfu commented
Could you resolve the conflicts as well? Thanks.

2021-02-27 15:21 UTC, merged