feat: add vite-aliases
vitejs/awesome-vite pull request #66
Opened 2021-01-21 12:19 UTC by Subwaytime

### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [x ] Pull request template structure not broken

### `Type`

> ℹ️  What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Fix
- [ x] Feature 

### `Checklist`

> ℹ️  Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](https://github.com/vuejs/awesome-vue/blob/master/.github/contributing.md).

> 👉  _Put an `x` in the boxes that apply._

- [ x] Title as described.
- [ ] Make sure you put things in the right category!
- [ x] Always add your items to the end of a list.
- [ ] Your plugin/tool is working with Vite 2.0 and onward.

#### `Open Source`

- [ x] Link description does not contain a link to an author / third-party resource
- [x ] The documentation (README) contains a description of the project, illustration of the project with a demo or screenshots and a CONTRIBUTING section
- [ x] The documentation is in English.
- [x ] The project is active and maintained.
- [ x] The project accepts contributions.
- [x ] Not a commercial product

#### `Apps/Websites`

- [ ] The website is available without errors or ssl certificate problems, and load in a reasonable amount of time.
- [ ] The website is using Vite intensively.
- [ ] The website is original and not too simple. For that reason, blogs and simple landing pages are rejected.
- [ ] A commercial product using Vite, provided that guests could reasonably check out how Vite was used A commercial product using Vite, provided that guests could reasonably check out how Vite was used (i.e. A headless CMS which uses Vite for the Admin/editor Area and offers a free tier).

2021-01-21 12:20 UTC, Subwaytime commented
Atm, there are Issues with MacOs and Unix (Linux). 
Till this is resolved on `vite-aliases` Site, it wont work perfectly with Vite 2.

2021-02-17 12:31 UTC, Subwaytime commented
Next Version of `vite-aliases` will include MacOs and Unix Support with Vite 2.
Release will be later today!

2021-02-27 15:22 UTC, antfu commented
Is it ready now?

2021-02-28 13:58 UTC, Subwaytime commented
Yes! :)

2021-02-28 14:36 UTC, antfu commented
I think we can move this to the "framework-agnostic" section.

2021-03-01 17:03 UTC, Subwaytime commented
"framework-agnostic" --> helpers ?

2021-03-02 17:10 UTC, Subwaytime commented
Done!

2021-03-03 01:42 UTC, antfu commented
Can you fix the merging conflicts? Thanks

2021-03-06 10:32 UTC, Subwaytime commented
Should be resolved.. i hope atleast ^^

2021-03-07 05:20 UTC, antfu commented on README.md
> +- [vite-aliases](https://github.com/subwaytime/vite-aliases) - Alias auto generation based on Projectstructure.
Should move to L154

2021-03-09 10:40 UTC, antfu requested changes
Please see the comments

2021-03-11 22:19 UTC, closed without merging