Add vite-imagetools to loader list
vitejs/awesome-vite pull request #82
Opened 2021-02-01 20:38 UTC by JonasKruckenberg

### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [x] Pull request template structure not broken

### `Type`

> ℹ️  What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Fix
- [x] Feature 

### `Checklist`

> ℹ️  Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](https://github.com/vuejs/awesome-vue/blob/master/.github/contributing.md).

> 👉  _Put an `x` in the boxes that apply._

- [x] Title as described.
- [x] Make sure you put things in the right category!
- [x] Always add your items to the end of a list.
- [x] Your plugin/tool is working with Vite 2.0 and onward.

#### `Open Source`

- [x] Link description does not contain a link to an author / third-party resource
- [ x The documentation (README) contains a description of the project, illustration of the project with a demo or screenshots and a CONTRIBUTING section
- [x] The documentation is in English.
- [x] The project is active and maintained.
- [x] The project accepts contributions.
- [x] Not a commercial product

#### `Apps/Websites`

- [ ] The website is available without errors or ssl certificate problems, and load in a reasonable amount of time.
- [ ] The website is using Vite intensively.
- [ ] The website is original and not too simple. For that reason, blogs and simple landing pages are rejected.
- [ ] A commercial product using Vite, provided that guests could reasonably check out how Vite was used A commercial product using Vite, provided that guests could reasonably check out how Vite was used (i.e. A headless CMS which uses Vite for the Admin/editor Area and offers a free tier).

2021-02-02 09:21 UTC, antfu commented
Is it framework agnostic?

2021-02-02 09:50 UTC, JonasKruckenberg commented
Not quite yet, it relies on vites asset loader at the moment.
I have some plans to change that but I don't know when

2021-02-11 15:49 UTC, antfu requested changes
Please move to the "Framework-agnostic Plugins" section.

2021-02-11 15:49 UTC, antfu commented on README.md
> +- [vite-imagetools](https://github.com/JonasKruckenberg/vite-imagetools) - Load and transform Images using a modular workflow.
```suggestion
- [vite-imagetools](https://github.com/JonasKruckenberg/vite-imagetools) - Load and transform images using url query.
```

2021-02-12 08:41 UTC, antfu commented on README.md
> +- [vite-imagetools](https://github.com/JonasKruckenberg/vite-imagetools) - Load and transform Images using a modular workflow.
```suggestion
- [vite-imagetools](https://github.com/JonasKruckenberg/vite-imagetools) - Load and transform images using a modular workflow.
```

2021-02-12 08:51 UTC, JonasKruckenberg commented
Sorry @antfu didn't see the request,  but should all be good now right?

2021-02-12 08:52 UTC, merged